cc_library(
    name = "square_adapter",
    hdrs = [
        "public/adapter/square_adapter.h",
    ],
)

cc_test(
    name = "square_adapter_test",
    srcs = ["square_adapter_test.cc"],
    deps = [
        ":square_adapter",
        "@com_google_googletest//:gtest_main",
    ],
)
